# build:
#   image: eboraas/laravel
#   commands:
#     - chmod -R 777 storage/
#     - chmod -R 777 bootstrap/cache/
#     - composer install
#     - cp .env.example .env
#     - php artisan key:generate
#     - vendor/bin/phpunit tests/

# deploy:
#   ssh:
#     host: 13.67.63.4
#     user: root
#     port: 8022
#     commands:
#       - cd /deploy
#       - ansible-playbook -i production  main.yml

deploy:
  ssh:
    image: framgia/ansible-drone
    host: 10.0.1.126
    user: root
    port: 22
    commands:
      - ls -la /root/.ssh
      - ansible all -m ping -i .ansible/production -vvv
      - ssh -v -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=8222 -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.0.1.126
      # - ansible-playbook -i .ansible/production .ansible/site.yml