# build:
#   image: eboraas/laravel
#   commands:
#     - chmod -R 777 storage/
#     - chmod -R 777 bootstrap/cache/
#     - composer install
#     - cp .env.example .env
#     - php artisan key:generate
#     - vendor/bin/phpunit tests/

# deploy:
#   ssh:
#     host: 13.67.63.4
#     user: root
#     port: 8022
#     commands:
#       - cd /deploy
#       - ansible-playbook -i production  main.yml

deploy:
  ssh:
    image: framgia/ansible-drone
    host: 172.17.0.3
    user: root
    port: 22
    commands:
      - ls -la /drone/src/.ansible
      - ansible-playbook -i /drone/src/.ansible/staging /drone/src/.ansible/site.yml